version: '3.8'

services:
  dev-mariadb:
    image: mariadb:11.3
    container_name: dev_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: testdb
      MARIADB_USER: testuser
      MARIADB_PASSWORD: testpass
      TZ: Asia/Seoul
    ports:
      - "3307:3306" # 배포용과 충돌 방지를 위해 3307 사용
    volumes:
      - dev_mariadb_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  dev_mariadb_data:
