# 라즈베리파이에서 테스트를 위한 환경 설정
server:
  port: 8090
spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    # 컨테이너 내부에서 `localhost`는 해당 컨테이너 자신을 가리키기 때문에, MariaDB 서비스의 이름인 `mariadb`를 사용
    # jdbc:mariadb://localhost:3306/${DB_NAME} ㄴㄴ
    username: ${DB_USERNAME}
    password: ${DB_USER_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  hikari: # [마리아 DB 떄매]
    connection-timeout: 60000 # [마리아 DB 떄매]
    initialization-fail-timeout: -1  # 무한 재시도 # [마리아 DB 떄매]
  jpa:
    hibernate:
      ddl-auto: update  # 또는 create, validate 등을 설정 가능
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true  # 데이터소스 초기화 지연 # [마리아 DB 떄매]
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: dontgoback.kro.kr/api/login/oauth2/code/google
jwt:
  secretKey: ${JWT_SECRET_KEY}

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
