# Auth, kakao ?? ?? ??? ?? ??
# git? ??? ?? ???? ??? ?????.
# ?? ?? ????? ?? ?? ?? ??? ???? ? ?? ?
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: CLIENT_ID
  mail:
    password: NEED_TO_INPUT
  custom:
    security:
      oath2:
        client:
          registration:
            kakao:
              devUser:
                oauthId: ouathId
                nickname: nickname