"use client";

import "./globals.css";

import SideBar from "../(layout)/components/Sidebar";
import { FeedProvider } from "./contexts/FeedContext";
import { UserProvider } from "./contexts/UserContext";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
        <UserProvider>
          <FeedProvider>
            <SideBar />
            {/* <Header/> */}
            <div className="main-layout">
              <div className="sidebar-space" />
              <div className="main-space">{children}</div>
            </div>
          </FeedProvider>
        </UserProvider>
      </body>
    </html>
  );
}
