name: Build and Push to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동으로 액션 실행

env:
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: 651706767183.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_REPO: dontgoback
  TAG: ${{ github.sha }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Backend
        working-directory: ./dontgo
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO:backend-$TAG .
          docker push $ECR_REGISTRY/$ECR_REPO:backend-$TAG

      - name: Build and Push Frontend
        working-directory: ./frontend_v2
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO:frontend-$TAG .
          docker push $ECR_REGISTRY/$ECR_REPO:frontend-$TAG

      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i ~/.ssh/ec2_key.pem \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} \
            "if grep -q '^TAG=' /home/ubuntu/.env; then \
                sed -i 's/^TAG=.*/TAG=${TAG}/' /home/ubuntu/.env; \
              else \
                echo 'TAG=${TAG}' >> /home/ubuntu/.env; \
              fi && \
              docker login -u AWS -p $(aws ecr get-login-password --region $AWS_REGION) $ECR_REGISTRY && \
              docker pull $ECR_REGISTRY/$ECR_REPO:backend-$TAG && \
              docker pull $ECR_REGISTRY/$ECR_REPO:frontend-$TAG && \
              docker-compose -f /home/ubuntu/docker-compose.yml up -d"
