name: Build and Push to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2
  ECR_REGISTRY: 651706767183.dkr.ecr.$AWS_REGION.amazonaws.com
  BACKEND_IMAGE: $ECR_REGISTRY/my-backend
  FRONTEND_IMAGE: $ECR_REGISTRY/my-frontend
  TAG: ${{ github.sha }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Backend
        working-directory: ./dontgo
        run: |
          docker build -t $BACKEND_IMAGE:$TAG .
          docker push $BACKEND_IMAGE:$TAG

      - name: Build and Push Frontend
        working-directory: ./frontend_v2
        run: |
          docker build -t $FRONTEND_IMAGE:$TAG .
          docker push $FRONTEND_IMAGE:$TAG